// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0YYEwf73cDrZgizxtugTXBpcCVreajHE',
    appId: '1:128661540132:web:818dfed0c52dd20caef7b1',
    messagingSenderId: '128661540132',
    projectId: 'progettoprogrammazione-858f6',
    authDomain: 'progettoprogrammazione-858f6.firebaseapp.com',
    databaseURL: 'https://progettoprogrammazione-858f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'progettoprogrammazione-858f6.appspot.com',
    measurementId: 'G-3JQ6H4DNVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNDSVPCltSCx7LCq2s320mK266N0D7084',
    appId: '1:128661540132:android:8d484485e4d9eaebaef7b1',
    messagingSenderId: '128661540132',
    projectId: 'progettoprogrammazione-858f6',
    databaseURL: 'https://progettoprogrammazione-858f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'progettoprogrammazione-858f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAN9QQVXA5OdFhKwAwTsQeumT_N63elmI',
    appId: '1:128661540132:ios:37c1f7ed2f863afbaef7b1',
    messagingSenderId: '128661540132',
    projectId: 'progettoprogrammazione-858f6',
    databaseURL: 'https://progettoprogrammazione-858f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'progettoprogrammazione-858f6.appspot.com',
    iosClientId: '128661540132-1gnomj9nc9s43gld54jhvfh526hp1ou1.apps.googleusercontent.com',
    iosBundleId: 'com.example.progettoProgrammazioneIos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAN9QQVXA5OdFhKwAwTsQeumT_N63elmI',
    appId: '1:128661540132:ios:37c1f7ed2f863afbaef7b1',
    messagingSenderId: '128661540132',
    projectId: 'progettoprogrammazione-858f6',
    databaseURL: 'https://progettoprogrammazione-858f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'progettoprogrammazione-858f6.appspot.com',
    iosClientId: '128661540132-1gnomj9nc9s43gld54jhvfh526hp1ou1.apps.googleusercontent.com',
    iosBundleId: 'com.example.progettoProgrammazioneIos',
  );
}
